In [7]:
pip install pandas

^C
Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: pandas in c:\users\madhu\appdata\roaming\python\python311\site-packages (2.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\madhu\appdata\roaming\python\python311\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\madhu\appdata\roaming\python\python311\site-packages (from pandas) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in c:\users\madhu\appdata\roaming\python\python311\site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in c:\users\madhu\appdata\roaming\python\python311\site-packages (from pandas) (1.23.5)
Requirement already satisfied: six>=1.5 in c:\users\madhu\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [3]:
import requests
import pandas as pd
from datetime import datetime

url = "https://earthquake.usgs.gov/fdsnws/event/1/query"

all_records = []
start_year = datetime.now().year - 5   # last 5 years
end_year = datetime.now().year

for year in range(start_year, end_year + 1):
    for month in range(1, 13):
        start_date = f"{year}-{month:02d}-01"
        if month == 12:
            end_date = f"{year+1}-01-01"
        else:
            end_date = f"{year}-{month+1:02d}-01"

        params = {
            "format": "geojson",
            "starttime": start_date,
            "endtime": end_date,
            "minmagnitude": 3
        }

        response = requests.get(url, params=params)
        if response.status_code != 200:
            print(f"⚠️ Failed for {start_date}: {response.text[:200]}")
            continue

        try:
            data = response.json()
        except Exception as e:
            print(f"⚠️ JSON error for {start_date}: {e}")
            continue

        for f in data["features"]:
            p = f["properties"]
            g = f["geometry"]["coordinates"]
            all_records.append({
                "id": f.get("id"),
                "time": pd.to_datetime(p.get("time"), unit="ms"),
                "updated": pd.to_datetime(p.get("updated"), unit="ms"),
                "latitude": g[1] if g else None,
                "longitude": g[0] if g else None,
                "depth_km": g[2] if g else None,
                "mag": p.get("mag"),
                "magType": p.get("magType"),
                "place": p.get("place"),
                "status": p.get("status"),
                "tsunami": p.get("tsunami"),
                "alert": p.get("alert"),
                "felt": p.get("felt"),
                "cdi": p.get("cdi"),
                "mmi": p.get("mmi"),
                "sig": p.get("sig"),
                "net": p.get("net"),
                "code": p.get("code"),
                "ids": p.get("ids"),
                "sources": p.get("sources"),
                "types": p.get("types"),
                "nst": p.get("nst"),
                "dmin": p.get("dmin"),
                "rms": p.get("rms"),
                "gap": p.get("gap"),
                "type": p.get("type")
            })

df = pd.DataFrame(all_records)

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print(df.head())

Rows: 112183
Columns: 26
           id                    time                 updated  latitude
0  us6000ddi8 2021-01-31 23:20:49.923 2021-04-16 19:02:44.040  -31.7493  \
1  us6000dev6 2021-01-31 23:08:17.161 2021-04-16 19:03:47.040  -15.4902
2  us6000dev5 2021-01-31 22:54:19.760 2021-04-16 19:03:47.040   19.7529
3  us6000ddhs 2021-01-31 22:06:00.832 2021-04-16 19:02:43.040   28.1524
4  us6000dev4 2021-01-31 21:51:14.016 2021-04-16 19:03:46.040   71.3212

   longitude  depth_km  mag magType
0   -68.9337     17.27  4.7     mwr  \
1  -177.2052    426.71  4.1      mb
2   121.3159     46.73  4.7      mb
3    57.2570     10.00  4.9      mb
4    -3.7578     10.00  4.0      mb

                                               place    status  ...  net
0        29 km SW of Villa Basilio Nievas, Argentina  reviewed  ...   us  \
1                                        Fiji region  reviewed  ...   us
2                    103 km SW of Basco, Philippines  reviewed  ...   us
3                            114 km N of M?n?b, Iran  reviewed  ...   us
4  184 km ENE of Olonkinbyen, Svalbard and Jan Mayen  reviewed  ...   us

       code           ids  sources                                   types
0  6000ddi8  ,us6000ddi8,     ,us,  ,dyfi,moment-tensor,origin,phase-data,  \
1  6000dev6  ,us6000dev6,     ,us,                     ,origin,phase-data,
2  6000dev5  ,us6000dev5,     ,us,                     ,origin,phase-data,
3  6000ddhs  ,us6000ddhs,     ,us,                     ,origin,phase-data,
4  6000dev4  ,us6000dev4,     ,us,                     ,origin,phase-data,

   nst   dmin   rms    gap        type
0  NaN  0.294  0.82   42.0  earthquake
1  NaN  1.471  0.29   64.0  earthquake
2  NaN  3.057  0.69  106.0  earthquake
3  NaN  3.330  0.61   71.0  earthquake
4  NaN  6.023  0.50   65.0  earthquake

[5 rows x 26 columns]

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112183 entries, 0 to 112182
Data columns (total 32 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   id                   112183 non-null  object
 1   time                 112183 non-null  datetime64[ns]
 2   updated              112183 non-null  datetime64[ns]
 3   latitude             112183 non-null  float64
 4   longitude            112183 non-null  float64
 5   depth_km             112183 non-null  float64
 6   mag                  112183 non-null  float64
 7   magType              112183 non-null  object
 8   place                112183 non-null  object
 9   status               112183 non-null  object
 10  tsunami              112183 non-null  int64
 11  alert                112183 non-null  object
 12  felt                 112183 non-null  float64
 13  cdi                  112183 non-null  float64
 14  mmi                  112183 non-null  float64
 15  sig                  112183 non-null  int64
 16  net                  112183 non-null  object
 17  code                 112183 non-null  object
 18  ids                  112183 non-null  object
 19  sources              112183 non-null  object
 20  types                112183 non-null  object
 21  nst                  112183 non-null  float64
 22  dmin                 112183 non-null  float64
 23  rms                  112183 non-null  float64
 24  gap                  112183 non-null  float64
 25  type                 112183 non-null  object
 26  Year                 112183 non-null  int32
 27  day_of_week          112183 non-null  object
 28  Month                112183 non-null  object
 29  Day                  112183 non-null  int32
 30  Flag_based_on_depth  112183 non-null  object
 31  Flag_based_on_mag    112183 non-null  object
dtypes: datetime64[ns](2), float64(11), int32(2), int64(2), object(15)
memory usage: 26.5+ MB

In [5]:
df['alert'].unique()

array([None, 'yellow', 'green', 'orange', 'red'], dtype=object)

In [6]:
df.isnull().sum()

id                0
time              0
updated           0
latitude          0
longitude         0
depth_km          0
mag               0
magType           0
place             0
status            0
tsunami           0
alert        107596
felt          94940
cdi           94940
mmi          102572
sig               0
net               0
code              0
ids               0
sources           0
types             0
nst           27761
dmin           3974
rms              18
gap            3021
type              0
dtype: int64

In [7]:
df

,id,time,updated,latitude,longitude,depth_km,mag,magType,place,status,...,net,code,ids,sources,types,nst,dmin,rms,gap,type
0,us6000ddi8,2021-01-31 23:20:49.923,2021-04-16 19:02:44.040,-31.749300,-68.933700,17.27,4.70,mwr,"29 km SW of Villa Basilio Nievas, Argentina",reviewed,...,us,6000ddi8,",us6000ddi8,",",us,",",dyfi,moment-tensor,origin,phase-data,",NaN,0.2940,0.82,42.0,earthquake
1,us6000dev6,2021-01-31 23:08:17.161,2021-04-16 19:03:47.040,-15.490200,-177.205200,426.71,4.10,mb,Fiji region,reviewed,...,us,6000dev6,",us6000dev6,",",us,",",origin,phase-data,",NaN,1.4710,0.29,64.0,earthquake
2,us6000dev5,2021-01-31 22:54:19.760,2021-04-16 19:03:47.040,19.752900,121.315900,46.73,4.70,mb,"103 km SW of Basco, Philippines",reviewed,...,us,6000dev5,",us6000dev5,",",us,",",origin,phase-data,",NaN,3.0570,0.69,106.0,earthquake
3,us6000ddhs,2021-01-31 22:06:00.832,2021-04-16 19:02:43.040,28.152400,57.257000,10.00,4.90,mb,"114 km N of M?n?b, Iran",reviewed,...,us,6000ddhs,",us6000ddhs,",",us,",",origin,phase-data,",NaN,3.3300,0.61,71.0,earthquake
4,us6000dev4,2021-01-31 21:51:14.016,2021-04-16 19:03:46.040,71.321200,-3.757800,10.00,4.00,mb,"184 km ENE of Olonkinbyen, Svalbard and Jan Mayen",reviewed,...,us,6000dev4,",us6000dev4,",",us,",",origin,phase-data,",NaN,6.0230,0.50,65.0,earthquake
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112178,pr71515233,2026-05-01 02:13:24.250,2026-05-01 02:36:25.820,18.548500,-66.297000,97.47,3.22,md,"10 km NNE of Brenas, Puerto Rico",reviewed,...,pr,71515233,",us7000shgg,pr71515233,",",us,pr,",",origin,phase-data,",41.0,0.2318,0.20,188.0,earthquake
112179,nc75354667,2026-05-01 01:58:41.390,2026-05-01 05:57:21.998,40.301167,-124.572167,9.03,3.69,mw,"24 km W of Petrolia, CA",reviewed,...,nc,75354667,",nc75354667,us7000shgd,",",nc,us,",",dyfi,moment-tensor,nearby-cities,origin,phase...",64.0,0.1761,0.22,239.0,earthquake
112180,aka2026intneh,2026-05-01 01:26:59.448,2026-05-07 01:11:31.451,53.881000,-162.804000,0.30,3.00,ml,"115 km SSE of False Pass, Alaska",reviewed,...,ak,a2026intneh,",aka2026intneh,",",ak,",",origin,phase-data,",26.0,0.9000,0.50,247.0,earthquake
112181,pr71515218,2026-05-01 01:02:05.820,2026-05-01 01:21:41.770,19.161333,-66.767500,25.62,3.08,md,"74 km N of Hatillo, Puerto Rico",reviewed,...,pr,71515218,",pr71515218,",",pr,",",origin,phase-data,",16.0,0.7170,0.11,258.0,earthquake
112182,us7000shg3,2026-05-01 00:49:08.843,2026-05-17 21:32:59.040,-42.198400,-18.399600,10.00,5.00,mb,southern Mid-Atlantic Ridge,reviewed,...,us,7000shg3,",us7000shg3,",",us,",",origin,phase-data,",40.0,33.1140,0.71,66.0,earthquake

In [8]:
alert_mode=df['alert'].mode()[0] # mode returns series of values so here we are taking only the first value

In [9]:
df['alert']=df['alert'].fillna(alert_mode)

In [10]:
alert_mode

'green'

In [11]:
df['alert'].unique() # no none values present

array(['green', 'yellow', 'orange', 'red'], dtype=object)

In [12]:
felt_mean = round(df["felt"].mean())
felt_mean

99

In [13]:
df['felt']=df['felt'].fillna(felt_mean)

In [14]:
df['felt']

0         12.0
1         99.0
2         99.0
3         99.0
4         99.0
          ...
112178    99.0
112179     2.0
112180    99.0
112181    99.0
112182    99.0
Name: felt, Length: 112183, dtype: float64

In [15]:
df['cdi']=round((df['cdi'].fillna(df['cdi'].mean())),1)

In [16]:
df['cdi']

0         3.7
1         3.2
2         3.2
3         3.2
4         3.2
         ...
112178    3.2
112179    2.0
112180    3.2
112181    3.2
112182    3.2
Name: cdi, Length: 112183, dtype: float64

In [17]:
df['mmi']=round((df['mmi'].fillna(df['mmi'].mean())),3)

In [18]:
df['mmi']

0         3.276
1         3.276
2         3.276
3         3.276
4         3.276
          ...
112178    3.276
112179    2.558
112180    3.276
112181    3.276
112182    3.276
Name: mmi, Length: 112183, dtype: float64

In [19]:
df['nst']=df['nst'].fillna(df['nst'].median())

In [20]:
df["nst"]

0         32.0
1         32.0
2         32.0
3         32.0
4         32.0
          ...
112178    41.0
112179    64.0
112180    26.0
112181    16.0
112182    40.0
Name: nst, Length: 112183, dtype: float64

In [21]:
df['dmin']=round((df['dmin'].fillna(df['dmin'].mean())),4)

In [22]:
df['rms']=round((df['rms'].fillna(df['rms'].mean())),2)

In [23]:
df["gap"].mean()

122.42718969440233

In [24]:
df['gap']=round(df['gap'].fillna(df['gap'].mean()))

In [25]:
df["place"] = df["place"].apply(lambda x: x.split(",")[-1].strip())

In [26]:
df['place']

0                           Argentina
1                         Fiji region
2                         Philippines
3                                Iran
4              Svalbard and Jan Mayen
                     ...
112178                    Puerto Rico
112179                             CA
112180                         Alaska
112181                    Puerto Rico
112182    southern Mid-Atlantic Ridge
Name: place, Length: 112183, dtype: object

In [27]:
df['alert']=df['alert'].str.lower()

In [28]:
cols = ['ids', 'sources', 'types']
df[cols] = df[cols].apply(lambda x: x.str.strip(',') )

In [29]:
#Year, month, day, day_of_week from time.
df["Year"] = df['time'].dt.year

In [30]:
df["day_of_week"] = df['time'].dt.day_name()

In [31]:
df['time'].dt.day_name()

0         Sunday
1         Sunday
2         Sunday
3         Sunday
4         Sunday
           ...
112178    Friday
112179    Friday
112180    Friday
112181    Friday
112182    Friday
Name: time, Length: 112183, dtype: object

In [32]:
df["Year"]

0         2021
1         2021
2         2021
3         2021
4         2021
          ...
112178    2026
112179    2026
112180    2026
112181    2026
112182    2026
Name: Year, Length: 112183, dtype: int32

In [33]:
df["Month"] = df['time'].dt.month_name()

In [34]:
df['time'].dt.month_name()

0         January
1         January
2         January
3         January
4         January
           ...
112178        May
112179        May
112180        May
112181        May
112182        May
Name: time, Length: 112183, dtype: object

In [35]:
df["Day"]= df["time"].dt.day

In [36]:
df["Day"]

0         31
1         31
2         31
3         31
4         31
          ..
112178     1
112179     1
112180     1
112181     1
112182     1
Name: Day, Length: 112183, dtype: int32

In [37]:
df["Month"]

0         January
1         January
2         January
3         January
4         January
           ...
112178        May
112179        May
112180        May
112181        May
112182        May
Name: Month, Length: 112183, dtype: object

“An earthquake is classified as Shallow if its depth is less than or equal to 70 km, and Deep if its depth is greater than 70 km.”

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112183 entries, 0 to 112182
Data columns (total 30 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   id           112183 non-null  object
 1   time         112183 non-null  datetime64[ns]
 2   updated      112183 non-null  datetime64[ns]
 3   latitude     112183 non-null  float64
 4   longitude    112183 non-null  float64
 5   depth_km     112183 non-null  float64
 6   mag          112183 non-null  float64
 7   magType      112183 non-null  object
 8   place        112183 non-null  object
 9   status       112183 non-null  object
 10  tsunami      112183 non-null  int64
 11  alert        112183 non-null  object
 12  felt         112183 non-null  float64
 13  cdi          112183 non-null  float64
 14  mmi          112183 non-null  float64
 15  sig          112183 non-null  int64
 16  net          112183 non-null  object
 17  code         112183 non-null  object
 18  ids          112183 non-null  object
 19  sources      112183 non-null  object
 20  types        112183 non-null  object
 21  nst          112183 non-null  float64
 22  dmin         112183 non-null  float64
 23  rms          112183 non-null  float64
 24  gap          112183 non-null  float64
 25  type         112183 non-null  object
 26  Year         112183 non-null  int32
 27  day_of_week  112183 non-null  object
 28  Month        112183 non-null  object
 29  Day          112183 non-null  int32
dtypes: datetime64[ns](2), float64(11), int32(2), int64(2), object(13)
memory usage: 24.8+ MB

In [39]:
df['Flag_based_on_depth']=df["depth_km"].apply(lambda x: 'Shallow' if x<=70 else 'deep')

“An earthquake is flagged as Strong if its magnitude is less than 7.0, and Destructive if its magnitude is greater than or equal to 7.0.”

In [40]:
df["Flag_based_on_mag"]=df["mag"].apply(lambda x: 'strong' if x <=7 else 'destructive')

In [48]:
df = df.rename(columns={'day_of_week': 'Day_of_week'})

In [ ]:
df['Flag_based_on_depth']=df['Flag_based_on_depth'].str.lower()

In [56]:
df['Flag_based_on_mag'].unique()

array(['strong', 'destructive'], dtype=object)

In [59]:
df['id'].nunique()

112183

In [60]:
df['type'].unique()

array(['earthquake', 'mining explosion', 'ice quake',
       'experimental explosion', 'mine collapse', 'quarry blast',
       'volcanic eruption', 'landslide', 'Landslide', 'other event',
       'explosion'], dtype=object)

In [63]:
df['status'].unique()

array(['reviewed', 'automatic'], dtype=object)

In [66]:
df['nst'].describe()

count    112183.000000
mean         42.088133
std          34.739120
min           0.000000
25%          24.000000
50%          32.000000
75%          46.000000
max         619.000000
Name: nst, dtype: float64

In [61]:
df

,id,time,updated,latitude,longitude,depth_km,mag,magType,place,status,...,dmin,rms,gap,type,Year,Day_of_week,Month,Day,Flag_based_on_depth,Flag_based_on_mag
0,us6000ddi8,2021-01-31 23:20:49.923,2021-04-16 19:02:44.040,-31.749300,-68.933700,17.27,4.70,mwr,Argentina,reviewed,...,0.2940,0.82,42.0,earthquake,2021,Sunday,January,31,shallow,strong
1,us6000dev6,2021-01-31 23:08:17.161,2021-04-16 19:03:47.040,-15.490200,-177.205200,426.71,4.10,mb,Fiji region,reviewed,...,1.4710,0.29,64.0,earthquake,2021,Sunday,January,31,deep,strong
2,us6000dev5,2021-01-31 22:54:19.760,2021-04-16 19:03:47.040,19.752900,121.315900,46.73,4.70,mb,Philippines,reviewed,...,3.0570,0.69,106.0,earthquake,2021,Sunday,January,31,shallow,strong
3,us6000ddhs,2021-01-31 22:06:00.832,2021-04-16 19:02:43.040,28.152400,57.257000,10.00,4.90,mb,Iran,reviewed,...,3.3300,0.61,71.0,earthquake,2021,Sunday,January,31,shallow,strong
4,us6000dev4,2021-01-31 21:51:14.016,2021-04-16 19:03:46.040,71.321200,-3.757800,10.00,4.00,mb,Svalbard and Jan Mayen,reviewed,...,6.0230,0.50,65.0,earthquake,2021,Sunday,January,31,shallow,strong
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112178,pr71515233,2026-05-01 02:13:24.250,2026-05-01 02:36:25.820,18.548500,-66.297000,97.47,3.22,md,Puerto Rico,reviewed,...,0.2318,0.20,188.0,earthquake,2026,Friday,May,1,deep,strong
112179,nc75354667,2026-05-01 01:58:41.390,2026-05-01 05:57:21.998,40.301167,-124.572167,9.03,3.69,mw,CA,reviewed,...,0.1761,0.22,239.0,earthquake,2026,Friday,May,1,shallow,strong
112180,aka2026intneh,2026-05-01 01:26:59.448,2026-05-07 01:11:31.451,53.881000,-162.804000,0.30,3.00,ml,Alaska,reviewed,...,0.9000,0.50,247.0,earthquake,2026,Friday,May,1,shallow,strong
112181,pr71515218,2026-05-01 01:02:05.820,2026-05-01 01:21:41.770,19.161333,-66.767500,25.62,3.08,md,Puerto Rico,reviewed,...,0.7170,0.11,258.0,earthquake,2026,Friday,May,1,shallow,strong
112182,us7000shg3,2026-05-01 00:49:08.843,2026-05-17 21:32:59.040,-42.198400,-18.399600,10.00,5.00,mb,southern Mid-Atlantic Ridge,reviewed,...,33.1140,0.71,66.0,earthquake,2026,Friday,May,1,shallow,strong

In [67]:
df.to_excel('Earthquake_data.xlsx')

In [ ]:
pip install sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.49-cp311-cp311-win_amd64.whl (2.1 MB)
     ---------------------------------------- 2.1/2.1 MB 3.2 MB/s eta 0:00:00
Collecting greenlet>=1
  Downloading greenlet-3.5.1-cp311-cp311-win_amd64.whl (238 kB)
     -------------------------------------- 238.1/238.1 kB 3.7 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\madhu\appdata\roaming\python\python311\site-packages (from sqlalchemy) (4.15.0)
Installing collected packages: greenlet, sqlalchemy
Successfully installed greenlet-3.5.1 sqlalchemy-2.0.49
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
df

NameError: name 'df' is not defined

In [57]:
from sqlalchemy import create_engine




# Correct MySQL connection string
engine = create_engine("mysql+pymysql://root:madhu.1723@127.0.0.1:3306/gst")

In [58]:
df.to_sql(
    name='earthquake_data',   # table name
    con=engine,
    if_exists='replace',      # 'replace' drops existing table, 'append' adds rows
    index=False,              # don’t write DataFrame index as a column
    chunksize=1000            # insert in batches for efficiency
)

112183